---
- name: confluence | Create PostgreSQL user/database
  include_tasks: postgres.yml
  when: confluence_database_engine == "postgresql"
  tags:
    - postgres

- name: confluence | Install dependencies
  ansible.builtin.apt:
    name: fontconfig
    state: present
    
- name: confluence | Create path for confluence's folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ confluence_download_dir }}"
  tags:
    - install

- name: confluence | Download package
  get_url:
    dest: "{{ confluence_download_dir }}/confluence_installer"
    url: "{{ confluence_url }}"
    mode: '0755'
  register: confluence_downloaded
  tags:
    - install

- name: confluence | Update response
  template:
    src: response.varfile.j2
    dest: "/tmp/response.varfile"
    mode: 0644
  tags:
    - install

- name: Get stats of the FS object
  ansible.builtin.stat:
    path: "{{ confluence_installation_dir }}"
  register: p

- name: confluence | Installation
  shell: "{{ confluence_download_dir }}/confluence_installer -q -varfile /tmp/response.varfile;"
  when: p.stat.isdir is not defined

- name: confluence | Config
  include_tasks: config.yml
  tags:
    - config

- name: confluence | Configuring service
  ansible.builtin.service:
    name: confluence
    state: restarted

- name: confluence | Allow all access to confluence port
  ufw:
    rule: allow
    port: "{{ confluence_connector_port }}"
    proto: tcp

# register domain

- name: Register domain
  include_role:
    name: nginx-proxy
  vars:
    register_domain: "{{ confluence_domain }}"
    forward_port: "{{ confluence_connector_port }}"
    forward_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
